const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const P=require('../dist/progress.js');
const articles=JSON.parse(fs.readFileSync(path.join(__dirname,'../data/catalog.json'),'utf8'));
assert(articles.every(a=>a.defaultRead===false),'Public catalogue must not contain personal read defaults');
assert.equal(new Set(articles.map(a=>a.id)).size,articles.length);
assert.equal(new Set(articles.map(a=>a.url)).size,articles.length);
assert.deepEqual(articles.map(a=>a.date),articles.map(a=>a.date).sort());
const fixtures=[{id:'old-news',defaultRead:true},{id:'research',defaultRead:false},{id:'new-news',defaultRead:false}];
const batch='legacy-test';
let s=P.initialize(fixtures,null,null,batch);assert.deepEqual(s.readIds,['old-news']);
P.setRead(s,'old-news',false,1000);P.setRead(s,'research',true,2000);
let restored=P.initialize([...fixtures].reverse(),JSON.stringify(s),null,batch);
assert(!restored.entries['old-news'].read);assert(restored.entries.research.read);assert(!restored.entries['new-news'].read);
let old=P.initialize(fixtures,JSON.stringify({version:2,readIds:['research'],appliedBatches:[batch]}),null,batch);
assert(!old.entries['old-news'].read);assert(old.entries.research.read);
const b=JSON.parse(JSON.stringify(P.backup(restored,fixtures)));
P.setRead(restored,'research',false,3000);
assert(!P.mergeBackup(restored,b).state.entries.research.read,'Newer unread must survive an old backup');
const publicState=P.initialize(fixtures.map(a=>({...a,defaultRead:false})),null,null,'public-catalog-v1');
assert.equal(publicState.readIds.length,0);
assert(P.mergeBackup(publicState,b).state.entries.research.read,'Migrating to a new origin preserves imported read progress');
const before=JSON.stringify(publicState);
assert.throws(()=>P.mergeBackup(publicState,{...b,progress:{version:2,entries:{bad:{read:'yes'}}}}));
assert.equal(JSON.stringify(publicState),before);
console.log('Passed: public data contains no reading history; migration, new unread, stable IDs, backup merge and chronology.');
